const express = require('express');
const router = express.Router();

// Import route modules
const userRoutes = require('./user/user.route.js');
const responsibilityRoutes = require('./admin/responsibility/responsibility.route.js');
const roleRoutes = require('./admin/role/role.route.js');
const languageRoutes = require('./admin/language/language.route.js');
const countryRoutes = require('./admin/country/country.route.js');
const stateRoutes = require('./admin/state/state.route.js');
const cityRoutes = require('./admin/city/city.route.js');
const userCategoryRoutes = require('./admin/category/userCategory.route.js');
const propertiesCategoryRoutes = require('./admin/properties_category/propertiesCategory.route.js');
const propertiesStatusRoutes = require('./admin/properties_status/propertiesStatus.route.js');
const propertiesRoutes = require('./admin/properties/properties.route.js');
const subscriptionsRoutes = require('./admin/subscriptions/subscriptions.route.js');
const contractsCategoryRoutes = require('./admin/contracts_category/contractsCategory.route.js');
const contractsCompanyRoutes = require('./admin/contracts_company/contractsCompany.route.js');
const contractsContractorPersonRoutes = require('./admin/contracts_contractor_person/contractsContractorPerson.route.js');
const paymentModeRoutes = require('./admin/payment_mode/paymentMode.route.js');
const transactionRoutes = require('./admin/transaction/transaction.route.js');
const earningRoutes = require('./admin/earning/earning.route.js');
const areaRoutes = require('./admin/area/area.route.js');
const promoCodeRoutes = require('./admin/promo_code/promoCode.route.js');
const promoMapUserRoutes = require('./admin/promo_code_map_user/promoMapUser.route.js');
const contractsEnquiriesRoutes = require('./admin/contracts_enquiries/contractsEnquiries.route.js');
const bannerRoutes = require('./admin/banners/banners.route.js');
const auditlogRoutes = require('./admin/audit_log/auditLog.route.js');
const reviewsTypeRoutes = require('./admin/reviews_type/reviewsType.route.js');
const reviewsRoutes = require('./admin/reviews/reviews.route.js');
const userQueryRoutes = require('./admin/user_query/userQuery.route.js');
const termsConditionRoutes = require('./admin/terms_condition/termsCondition.route.js');
const privacyPolicyRoutes = require('./admin/privacy_policy/privacyPolicy.route.js');
const faqRoutes = require('./admin/faq/faq.route.js');
const pushNotificationRoutes = require('./admin/push_notification/pushNotification.route.js');
const ticketRoutes = require('./admin/ticket/ticket.route.js');
// Use routes
router.use('/user', userRoutes);
router.use('/responsibility', responsibilityRoutes);
router.use('/role', roleRoutes);
router.use('/language', languageRoutes);
router.use('/country', countryRoutes);
router.use('/state', stateRoutes);
router.use('/city', cityRoutes);
router.use('/user-category', userCategoryRoutes);
router.use('/properties-category', propertiesCategoryRoutes);
router.use('/properties-status', propertiesStatusRoutes);
router.use('/properties', propertiesRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/contracts-category', contractsCategoryRoutes);
router.use('/contracts-company', contractsCompanyRoutes);
router.use('/contracts-contractor-person', contractsContractorPersonRoutes);
router.use('/payment-mode', paymentModeRoutes);
router.use('/transaction', transactionRoutes);
router.use('/earning', earningRoutes);
router.use('/area', areaRoutes);
router.use('/promo-code', promoCodeRoutes);
router.use('/promo-code-map-user', promoMapUserRoutes);
router.use('/contracts-enquiries', contractsEnquiriesRoutes);
router.use('/banners', bannerRoutes);
router.use('/audit-log', auditlogRoutes);
router.use('/reviews-type', reviewsTypeRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/user-query', userQueryRoutes);
router.use('/terms-condition', termsConditionRoutes);
router.use('/privacy-policy', privacyPolicyRoutes);
router.use('/faq', faqRoutes);
router.use('/push-notification', pushNotificationRoutes);
router.use('/ticket', ticketRoutes);

module.exports = router;
