const express = require('express');
const router = express.Router();

// Import route modules
const userRoutes = require('./user/user.route.js');
const responsibilityRoutes = require('./admin/responsibility/responsibility.route.js');
const roleRoutes = require('./admin/role/role.route.js');
const languageRoutes = require('./admin/language/language.route.js');
const countryRoutes = require('./admin/country/country.route.js');
const stateRoutes = require('./admin/state/state.route.js');
const cityRoutes = require('./admin/city/city.route.js');
const userCategoryRoutes = require('./admin/category/userCategory.route.js');
const propertiesCategoryRoutes = require('./admin/properties_category/propertiesCategory.route.js');
const propertiesStatusRoutes = require('./admin/properties_status/propertiesStatus.route.js');
const propertiesRoutes = require('./admin/properties/properties.route.js');
const subscriptionsRoutes = require('./admin/subscriptions/subscriptions.route.js');
const contractsCategoryRoutes = require('./admin/contracts_category/contractsCategory.route.js');
const contractsCompanyRoutes = require('./admin/contracts_company/contractsCompany.route.js');
const contractsContractorPersonRoutes = require('./admin/contracts_contractor_person/contractsContractorPerson.route.js');
const paymentModeRoutes = require('./admin/payment_mode/paymentMode.route.js');
const transactionRoutes = require('./admin/transaction/transaction.route.js');
const earningRoutes = require('./admin/earning/earning.route.js');
const areaRoutes = require('./admin/area/area.route.js');
const promoCodeRoutes = require('./admin/promo_code/promoCode.route.js');
const promoMapUserRoutes = require('./admin/promo_code_map_user/promoMapUser.route.js');
const contractsEnquiriesRoutes = require('./admin/contracts_enquiries/contractsEnquiries.route.js');
const bannerRoutes = require('./admin/banners/banners.route.js');
const auditlogRoutes = require('./admin/audit_log/auditLog.route.js');
const reviewsTypeRoutes = require('./admin/reviews_type/reviewsType.route.js');
const reviewsRoutes = require('./admin/reviews/reviews.route.js');
const userQueryRoutes = require('./admin/user_query/userQuery.route.js');
const termsConditionRoutes = require('./admin/terms_condition/termsCondition.route.js');
const privacyPolicyRoutes = require('./admin/privacy_policy/privacyPolicy.route.js');
const faqRoutes = require('./admin/faq/faq.route.js');
const pushNotificationRoutes = require('./admin/push_notification/pushNotification.route.js');
const ticketRoutes = require('./admin/ticket/ticket.route.js');
const boostAdvertisementPlanRoutes = require('./admin/boost_advertisement_plan/boostAdvertisementPlan.route.js');
const boostAdvertisementOfferRoutes = require('./admin/boost_advertisement_offer/boostAdvertisementOffer.route.js');
const searchRoutes = require('./user/search/search.route.js');
const boostPropertiesRoutes = require('./user/boost_properties/boostProperties.route.js');
const propertiesSavedHomesRoutes = require('./user/properties_saved_homes/propertiesSavedHomes.route.js');
const propertiesSavedSearchesRoutes = require('./user/properties_saved_searches/propertiesSavedSearches.route.js');
const propertiesYourHomeRoutes = require('./user/properties_your_home/propertiesYourHome.route.js');
const propertiesRenterHubRoutes = require('./user/properties_renter_hub/propertiesRenterHub.route.js');
const propertiesRecentlyViewedRoutes = require('./user/properties_recently_viewed/propertiesRecentlyViewed.route.js');
const propertiesManageToursRoutes = require('./user/properties_manage_tours/propertiesManageTours.route.js');
const yourFavoritePropertiesRoutes = require('./user/your_favorite_properties/yourFavoriteProperties.route.js');
const planRoutes = require('./admin/plan/plan.route.js');
const planMapUserRoutes = require('./user/plan_map_user/planMapUser.route.js');
const industryGetStartedSellerRoutes = require('./user/industry_get_started_seller/industryGetStartedSeller.route.js');
const industryGetStartedManagerRoutes = require('./user/industry_get_started_manager/industryGetStartedManager.route.js');
const industryGetStartedLandlordRoutes = require('./user/industry_get_started_landlord/industryGetStartedLandlord.route.js');
const industryGetStartedRemodelingCompanyRoutes = require('./user/industry_get_started_remodeling_company/industryGetStartedRemodelingCompany.route.js');
const industryGetStartedLocalAdvertiserRoutes = require('./user/industry_get_started_local_advertiser/industryGetStartedLocalAdvertiser.route.js');
const giftCardsTypeRoutes = require('./admin/gift_cards_type/giftCardsType.route.js');
const couponsRoutes = require('./admin/coupons/coupons.route.js');
const giftCardsMapUserRoutes = require('./user/gift_cards_map_user/giftCardsMapUser.route.js');
const couponsMapUserRoutes = require('./user/coupons_map_user/couponsMapUser.route.js');
// Use routes
router.use('/user', userRoutes);
router.use('/responsibility', responsibilityRoutes);
router.use('/role', roleRoutes);
router.use('/language', languageRoutes);
router.use('/country', countryRoutes);
router.use('/state', stateRoutes);
router.use('/city', cityRoutes);
router.use('/user-category', userCategoryRoutes);
router.use('/properties-category', propertiesCategoryRoutes);
router.use('/properties-status', propertiesStatusRoutes);
router.use('/properties', propertiesRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/contracts-category', contractsCategoryRoutes);
router.use('/contracts-company', contractsCompanyRoutes);
router.use('/contracts-contractor-person', contractsContractorPersonRoutes);
router.use('/payment-mode', paymentModeRoutes);
router.use('/transaction', transactionRoutes);
router.use('/earning', earningRoutes);
router.use('/area', areaRoutes);
router.use('/promo-code', promoCodeRoutes);
router.use('/promo-code-map-user', promoMapUserRoutes);
router.use('/contracts-enquiries', contractsEnquiriesRoutes);
router.use('/banners', bannerRoutes);
router.use('/audit-log', auditlogRoutes);
router.use('/reviews-type', reviewsTypeRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/user-query', userQueryRoutes);
router.use('/terms-condition', termsConditionRoutes);
router.use('/privacy-policy', privacyPolicyRoutes);
router.use('/faq', faqRoutes);
router.use('/push-notification', pushNotificationRoutes);
router.use('/ticket', ticketRoutes);
router.use('/boost-advertisement-plan', boostAdvertisementPlanRoutes);
router.use('/boost-advertisement-offer', boostAdvertisementOfferRoutes);
router.use('/search', searchRoutes);
router.use('/boost-properties', boostPropertiesRoutes);
router.use('/properties-saved-homes', propertiesSavedHomesRoutes);
router.use('/properties-saved-searches', propertiesSavedSearchesRoutes);
router.use('/properties-your-home', propertiesYourHomeRoutes);
router.use('/properties-renter-hub', propertiesRenterHubRoutes);
router.use('/properties-recently-viewed', propertiesRecentlyViewedRoutes);
router.use('/properties-manage-tours', propertiesManageToursRoutes);
router.use('/your-favorite-properties', yourFavoritePropertiesRoutes);
router.use('/plan', planRoutes);
router.use('/plan-map-user', planMapUserRoutes);
router.use('/industry-get-started-seller', industryGetStartedSellerRoutes);
router.use('/industry-get-started-manager', industryGetStartedManagerRoutes);
router.use('/industry-get-started-landlord', industryGetStartedLandlordRoutes);
router.use('/industry-get-started-remodeling-company', industryGetStartedRemodelingCompanyRoutes);
router.use('/industry-get-started-local-advertiser', industryGetStartedLocalAdvertiserRoutes);
router.use('/gift-cards-type', giftCardsTypeRoutes);
router.use('/coupons', couponsRoutes);
router.use('/gift-cards-map-user', giftCardsMapUserRoutes);
router.use('/coupons-map-user', couponsMapUserRoutes);

module.exports = router;
